server:
  port: 8080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: stock-prediction-api
          uri: http://localhost:8081
          predicates:
            - Path=/stock/**
        - id: sentiment-news_analysis-api
          uri: http://localhost:8082
          predicates:
            - Path=/news/**
        - id: stock-purchase-api
          uri: http://localhost:8083
          predicates:
            - Path=/order/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

user-mgmt-api:
  base-url: http://localhost:8084
  path: /user